version: '3.7'
services:

  #######################################################
  #                     Drone CI                        #
  #######################################################

#  drone:
#    image: drone/drone:1
#    ports:
#      - "127.0.0.1:9080:80"
#      - "127.0.0.1:9443:443"
#    restart: always
#    volumes:
#    - "/var/lib/drone:/dat"
#    networks:
#      - drone
#
#  runner:
#    image: drone/drone-runner-docker:1
#    depends_on:
#      - drone
#    privileged: true
#    ports:
#    - "127.0.0.1:3000:3000"
#    restart: always
#    volumes:
#    - "/var/run/docker.sock:/var/run/docker.sock"
#    networks:
#      - drone


  #######################################################
  #                     WiseHub                         #
  #######################################################

#  db:
#    image: mysql:latest
#    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - "127.0.0.1:3306:3306"
#    networks:
#      - wisehub
#
#  adminer:
#    image: adminer:latest
#    depends_on:
#      - db
#    ports:
#      - "127.0.0.1:8081:8080"
#    networks:
#      - wisehub

  api:
    container_name: wisehub_api
    build: ./
    restart: always
    expose:
      - "9010"
      - "25"
    volumes:
      - ${PLUGIN_PATH}/plugins:/backend/model/plugins
    networks:
      - wisehub

  wisehub:
    container_name: wisehub
    build: ./view
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - wisehub


networks:
#  drone:
  wisehub: