version: '3.7'
services:

  #######################################################
  #                     Drone CI                        #
  #######################################################

#  drone:
#    image: drone/drone:1
#    environment:
#      DRONE_GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
#      DRONE_GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
#      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
#      DRONE_SERVER_HOST: 127.0.0.1
#      DRONE_SERVER_PROTO: http
#      DRONE_USER_CREATE: username:${USERNAME},admin:${ADMIN}
#    ports:
#      - "127.0.0.1:9080:80"
#      - "127.0.0.1:9443:443"
#    restart: always
#    volumes:
#    - "/var/lib/drone:/dat"
#    networks:
#      - drone
#
#  runner:
#    image: drone/drone-runner-docker:1
#    depends_on:
#      - drone
#    environment:
#      DRONE_RPC_PROTO: http
#      DRONE_RPC_HOST: drone
#      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
#      DRONE_RUNNER_CAPACITY: 2
#      DRONE_RUNNER_NAME: drone_runner
#      DRONE_DEBUG: 'true'
#      DRONE_TRACE: 'true'
#      DRONE_RPC_DUMP_HTTP: 'true'
#      DRONE_RPC_DUMP_HTTP_BODY: 'true'
#      DRONE_UI_USERNAME: root
#      DRONE_UI_PASSWORD: root
#    privileged: true
#    ports:
#    - "127.0.0.1:3000:3000"
#    restart: always
#    volumes:
#    - "/var/run/docker.sock:/var/run/docker.sock"
#    networks:
#      - drone


  #######################################################
  #                     WiseHub                         #
  #######################################################

#  db:
#    image: mysql:latest
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: test1234!!
#      MYSQL_DATABASE: wisehub
#      MYSQL_USER: wisehub
#      MYSQL_PASSWORD: test1234!!
#    ports:
#      - "127.0.0.1:3306:3306"
#    networks:
#      - wisehub
#
#  adminer:
#    image: adminer:latest
#    environment:
#      ADMINER_DEFAULT_SERVER: db
#    depends_on:
#      - db
#    ports:
#      - "127.0.0.1:8081:8080"
#    networks:
#      - wisehub

  api:
    container_name: api
    environment:
      DB_DRIVER: sqlite # Change to the official supported gorm.io/database_driver
      DB_NAME: wisehub.db # For sqlite: name of db-file; for other databases: database_name
      DB_USER: wisehub # database user
      DB_PASSWORD: test1234!! # database password
      DB_HOST: db # database host -> docker service name or localhost
      DB_PORT: 3306 # database port
      DB_SSL_MODE: disabled # 'disabled' or 'enabled' ssl mode
      CGO_ENBLED: 0
    build: ./
    restart: always
    expose:
      - "9010"
    volumes:
      - $HOME/plugins:/backend/model/plugins
    networks:
      - wisehub

  wisehub:
    container_name: wisehub
    build: ./view
    restart: always
    depends_on:
      - api
    ports:
      - "127.0.0.1:10080:80"
    networks:
      - wisehub


networks:
  drone:
  wisehub: