version: '3.7'
services:

  #######################################################
  #                     Drone CI                        #
  #######################################################

  drone:
    image: drone/drone:1
    environment:
      DRONE_GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      DRONE_GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: 127.0.0.1
      DRONE_SERVER_PROTO: http
      DRONE_USER_CREATE: username:${USERNAME},admin:${ADMIN}
    ports:
      - "127.0.0.1:9080:80"
      - "127.0.0.1:9443:443"
    restart: always
    volumes:
    - "/var/lib/drone:/dat"
    networks:
      - drone

  runner:
    image: drone/drone-runner-docker:1
    depends_on:
      - drone
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: drone_runner
      DRONE_DEBUG: 'true'
      DRONE_TRACE: 'true'
      DRONE_RPC_DUMP_HTTP: 'true'
      DRONE_RPC_DUMP_HTTP_BODY: 'true'
      DRONE_UI_USERNAME: root
      DRONE_UI_PASSWORD: root
    privileged: true
    ports:
    - "127.0.0.1:3000:3000"
    restart: always
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - drone


  #######################################################
  #                     WiseHub                         #
  #######################################################

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - wisehub

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - wisehub

  backend:
    container_name: wisehub_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
      labels:
        wisehub.title: "WiseHub - Backend"
        wisehub.description: "Backend in golang"
        wisehub.department: "IT"
    ports:
      - 9010:9010
    volumes:
      - ${PLUGIN_PATH}:/backend/model/plugins

  frontend:
    container_name: wisehub_frontend
    build:
      context: .
      dockerfile: Dockerfile.backend
      labels:
        wisehub.title: "WiseHub - Frontend"
        wisehub.description: "Frontend in VueJS"
        wisehub.department: "IT"
    depends_on:
      - backend
    ports:
      - 80:80


networks:
  drone:
  wisehub: