version: '3.7'
services:
  drone:
    image: drone/drone:1
    environment:
      DRONE_GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID
      DRONE_GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET
      DRONE_RPC_SECRET: $DRONE_RPC_SECRET
      DRONE_SERVER_HOST: 127.0.0.1
      DRONE_SERVER_PROTO: http
      DRONE_USER_CREATE: username:$USERNAME,admin:$ADMIN
    ports:
      - "127.0.0.1:9080:80"
      - "127.0.0.1:9443:443"
    restart: always
    volumes:
    - "/var/lib/drone:/dat"
    networks:
      - drone

  runner:
    image: drone/drone-runner-docker:1
    depends_on:
      - drone
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone
      DRONE_RPC_SECRET: $DRONE_RPC_SECRET
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: drone_runner
      DRONE_DEBUG: 'true'
      DRONE_TRACE: 'true'
      DRONE_RPC_DUMP_HTTP: 'true'
      DRONE_RPC_DUMP_HTTP_BODY: 'true'
      DRONE_UI_USERNAME: root
      DRONE_UI_PASSWORD: root
    privileged: yes
    ports:
    - "127.0.0.1:3000:3000"
    restart: always
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - drone

networks:
  drone: